import { type Metadata } from "next";
import Link from "next/link";
import { Icons } from "../_components/Icons";
import Menu from "../_components/Menu";
import NavBar from "../_components/Navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex h-screen">
      <div className="md:w[8%] w-[14%] p-4 lg:w-[16%] xl:w-[14%]">
        <Link href={"/"}>
          <div className="flex justify-center gap-2 lg:justify-start">
            <Icons.Logo className="size-6" />
            <span className="hidden lg:block">School</span>
          </div>
        </Link>
        <Menu />
      </div>
      <div className="md-[92%] flex w-[86%] flex-col overflow-scroll bg-primary-foreground p-4 lg:w-[84%] xl:w-[86%]">
        <NavBar />
        {children}
      </div>
    </div>
  );
}
